version: '3'
services:
  postgres:
    image: postgres:14.4
    container_name: db
    ports:
      - '5432:5432'
    volumes:
      - ./packages/db/prisma/entrypoint:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      APP_DB_NAME: cua-posts
